# Generated by Django 2.1.4 on 2019-05-23 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poem_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poet_recommendation.PoemAuthor')),
            ],
            options={
                'db_table': 'poems',
            },
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('yunlv_rule', models.TextField()),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='poetry', to='poet_recommendation.PoetryAuthor')),
            ],
            options={
                'db_table': 'poetry',
            },
        ),
    ]
