# Generated by Django 2.1.4 on 2019-05-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poet_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('yunlv_rule', models.TextField()),
                ('poem_type', models.CharField(max_length=20)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poet_recommendation.Poet')),
            ],
            options={
                'db_table': 'poem',
            },
        ),
    ]
