# Generated by Django 2.1.4 on 2019-05-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoemAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('intro_l', models.TextField()),
                ('intro_s', models.TextField()),
            ],
            options={
                'db_table': 'poems_author',
            },
        ),
        migrations.CreateModel(
            name='PoetryAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('intro', models.TextField()),
                ('dynasty', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'poetry_author',
            },
        ),
    ]
