# Generated by Django 2.1.4 on 2019-05-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='dynasty',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='poet',
            name='intro',
            field=models.TextField(default=''),
        ),
    ]
