# Generated by Django 2.1.4 on 2019-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet_recommendation', '0002_auto_20190523_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='dynasty',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='poet',
            name='intro',
            field=models.TextField(default='NULL'),
        ),
    ]
