# Generated by Django 2.1.4 on 2019-05-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet_recommendation', '0003_auto_20190523_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='dynasty',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='poet',
            name='intro',
            field=models.TextField(null=True),
        ),
    ]
